### ISSUE TITLE
Possible to assert AS towards motherboard only if access is to low 16 MB?

### ISSUE THREAD

**Issue by niklasekstrom** [terriblefire/tf1230#1]
Hi @terriblefire,

A user of PicoWyfy (https://github.com/niklasekstrom/picowyfy) that has an issue when it is used together with TF1232 pointed me to this forum post: https://www.exxosforum.co.uk/forum/viewtopic.php?p=91790

Would it make sense to update the logic for the AS signal towards the motherboard, by only asserting it if the top 8 bits of the address bus is 8'h00?

Perhaps something like: `AS20_D <= AS30 | ~SPEED_D | (A[31:24] != 8'h00);`
(taken from https://github.com/terriblefire/tf1230/blob/main/rtl/main_top.v#L274)

I'm thinking that this should prevent SPARE_CS from being asserted when an access is made to some address $xxD8yyyy where xx != 00.

I should say that I only looked at the rtl very quickly, so this may be incorrect for multiple reasons.

**Comment by terriblefire** [comment]
i spent an evening trying this with Rob Cranley. I could do that but the CS lines do not depend on AS. They decode whether or not AS is asserted

**Comment by niklasekstrom** [comment]
Oh, right, sorry. I looked in this document, https://www.amigawiki.org/lib/exe/fetch.php?media=de:parts:gayle_specification.pdf, where it says:

![image](https://github.com/terriblefire/tf1230/assets/6104627/14ab159f-5a63-4727-8ebf-35aa89019d84)
(`Chip select is based purely on address decode and _AS`)

But then when looking in this document, https://github.com/nonarkitten/amiga_replacement_project/blob/master/gayle/gayle_r5.pdf, it is as you say, SPARE_CS is based purely on address decode.

However, in that last document (gayle_r5.pdf) it also looks like AS needs to be asserted for IORD to be asserted. So keeping AS negated should prevent IORD from becoming asserted, and so should prevent the incorrect read access from the clockport device.

Actually, although not strictly necessary, perhaps DS20 should also be gated by A[31:24] == 8'h00?

`DS20_D <= DS30 | ~SPEED_D | (A[31:24] != 8'h00);`
(From https://github.com/terriblefire/tf1230/blob/main/rtl/main_top.v#L275)

**Comment by niklasekstrom** [comment]
Would it be easy (enough) for you to compile a firmware for TF1232 using these two changes (gating AS20_D and DS20_D)? In that case perhaps the guy who has the TF1232 + PicoWyfy combo could try that firmware and see if it helps.

**Comment by terriblefire** [comment]
I can but you need to understand it's irrelevant because SPEED_D is asserted when talking to fastram and that already prevents AS going low. I've investigated this issue thoroughly already.

**Comment by niklasekstrom** [comment]
SPEED_D (via ram_decode) doesn't seem to take A[26:24] into account though? Hence the problem with an access to the address 0x08D80000.

**Comment by terriblefire** [comment]
0x08D80000 would not assert AS/DS because A27 is logic 1. Anything in the range 08xxx xxxx will not assert AS. I've already measured this looking for this specific issue.

**Comment by niklasekstrom** [comment]
Ah right, so the address 0x07D80000 would cause a problem though?

**Comment by terriblefire** [comment]
Nothing in AmigaOS (A1200 version) should look at that address.

**Comment by terriblefire** [comment]
BTW. You can just try this yourself with the TF1230 code. The TF1232 is compatible with the TF1230 firmwares. You just dont get the FPU

**Comment by niklasekstrom** [comment]
Do you have the build environment set up so that it's very easy for you to compile a new firmware with those changes?

If not then I could try to set it up myself. But if I do then I still don't have a way to compile the TF1232 firmware with FPU support, so the user doesn't have any way to restore the firmware to get FPU support back.

The user reported that the problem showed up in two demos, so the demos may make accesses that AmigaOS wouldn't.

Just to be clear, I have no idea if the problem has anything to do with the TF firmware, I'm just trying to think of things to test, to help the user out.

**Comment by terriblefire** [comment]
I can put a test fw here. later if you need. 

The reason i didnt want to blank off AS here is because technically the CPU slot is 32bit address bus and there are CFGIN/OUT pins on it. I guess most CPU cards wont obey the rules but you can put a full Z3 32bit bus card between all the TF cards and an amiga they will work. i.e. it will be able to address a card at 0x40000000 for example

**Comment by niklasekstrom** [comment]
I checked with the guy, and he knows how to update the TF firmware as he did it recently. So if you could build a firmware with those changes then that would be most appreciated! And very interesting to see what happens.

**Comment by niklasekstrom** [comment]
I managed to compile the firmware in this repo with the changes mentioned. But apparently there are other issues with the user's Amiga, so he hasn't been able to test the changes. Perhaps the crashes were related to the other issues to begin with.

I'll close this issue for now, and if he later manages to test the changes then I will add information about how it went.

**Comment by terriblefire** [comment]
Ok thanks. if we can actually pin down an issue i'm happy to delve in and fix
